export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as ProductsPage } from './ProductsPage'
export { default as CartPage } from './CartPage'
export { default as ProductsDetailPage } from './ProductsDetailPage'
export { default as NotFound404Page } from './NotFound404Page'
